services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  tika:
    container_name: tika
    restart: on-failure
    image: apache/tika:latest-full

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - tika
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'TEXT_EXTRACTION_ENGINE=tika'
      - 'RAG_EMBEDDING_MODEL_AUTO_UPDATE=True'
      - 'RAG_RERANKING_MODEL_AUTO_UPDATE=True'
      - 'RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE=True'
      - 'RAG_RERANKING_MODEL_TRUST_REMOTE_CODE=True'
      - 'local_files_only=False'
      # does the last flag even do sth?
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
